version: "3.9"
services:
  exploit-tensorflow-vulnerability:
    container_name: exploit-tensorflow-vulnerability
    build:
      context: .
    networks:
      - backend

networks:
  backend:
    driver: bridge
