version: "3.9"
services:
  exploit-tensorflow-vulnerability:
    container_name: exploit-tensorflow-vulnerability
    build:
      context: .
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  backend:
    driver: bridge
